### ISSUE TITLE
Weird UnicodeEncodeError retrieving SP500 last week

### ISSUE THREAD

**Issue by elmotec** [mortada/fredapi#8] opened 2015-07-26 00:27 UTC
So not sure if I made a mistake last week but I was getting the following error when retrieving info about the SP500 with Python 2.7.10 (Python 3.4 was fine):
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 239
: ordinal not in range(128)
```
I can't be sure because I could not reproduce the problem today outside of the fake tests, but I figured the problem lied with the conjunction of (i) somehow getting an ascii response though it is advertised as being UTF-8 encoded, and (ii) having the copyright sign in the response which is the only non-ascii character I've seen from FRED.

Just putting it out there in case somebody noticed the issue too. I have a patch ready if the issue is verified (https://github.com/elmotec/fredapi/tree/fix_non_utf_chars_in_response).

**Comment by mortada** [comment] 2015-07-26 07:04
@elmotec I don't see this problem (using the current latest release of `fredapi` and python 2.7.10) 

```
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:04:42)
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from fredapi import Fred

In [2]: fred = Fred()

In [3]: data = fred.get_series('SP500', observation_start='9/2/2014')

In [4]: data.tail()
Out[4]:
2015-07-17    2126.64
2015-07-20    2128.28
2015-07-21    2119.21
2015-07-22    2114.15
2015-07-23    2102.15
dtype: float64
```

**Comment by elmotec** [comment] 2015-07-26 14:15
The issue I thought I had was related to `get_series_info()`, I made a note to myself to fix it (that is ignore bad characters) at the time, but I can't reproduce the issue anymore other than in a test (passing the SP500 info data as ASCII when it's advertised as UTF-8), so I am not sure what actually happened anymore.

It definitely is not occurring anymore.
```python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import fredapi
>>> fred = fredapi.Fred()
>>> fred.get_series_info('SP500')['title']
u'S&P 500\xa9'
```

I suspect the problem has to do with the &copy; symbol in SP500 info. We could close the issue since the problem cannot be reproduced, I'll keep my branch handy in case it happens again.

We could also integrate the "fix" to make fredapi more resilient to bad input. Note however that this branch is based on [@elmotec/master](https://github.com/elmotec/fredapi/tree/master) which is ahead of a few commits related to #5.

**Comment by mortada** [comment] 2015-07-26 14:27
hmm yeah this actually works for me just fine for both python2 and python3, including the © symbol. Let's close this for now and reopen if you reproduce it. Thanks.

**Closed** 2015-07-26 14:27 UTC
Labels: help wanted
